name: Build and Deploy Vue.js to Docker Hub

on:
  push:
    branches: 
      - "feature/**"  # Trigger for feature branches
      - main  # Trigger for main branch
  pull_request:
    branches: 
      - main  # Runs deployment for staging on PR open
    types: [opened, reopened, ready_for_review]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/my-vue-app  # Define image name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Use token instead of password

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.run_number }}
            ${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'  # Deploys only when PR is opened
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull the latest Docker image
        run: docker pull ${{ env.IMAGE_NAME }}:${{ github.run_number }}

      - name: Stop and remove old staging container
        run: |
          docker stop vue-staging || true
          docker rm vue-staging || true

      - name: Run updated staging container
        run: |
          docker run -d --name vue-staging -p 8081:80 ${{ env.IMAGE_NAME }}:${{ github.run_number }}

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull the latest Docker image
        run: docker pull ${{ env.IMAGE_NAME }}:${{ github.run_number }}

      - name: Stop and remove old production container
        run: |
          docker stop vue-nginx || true
          docker rm vue-nginx || true

      - name: Run updated production container
        run: |
          docker run -d --name vue-nginx -p 8080:80 ${{ env.IMAGE_NAME }}:${{ github.run_number }}
